eureka:
  client:
    service-url:
      # 指定eureka服务器的地址
      defaultZone: http://localhost:8761/eureka/ # ,http://localhost:8762/eureka/,http://localhost:8763/eureka/
#  设置主机名
#  instance:
#    hostname: clientName
spring:
  application:
    # 指定进行服务注册时该服务的名称
    name: client